#EXTM3U    x-tvg-url="http://botallen.live/epg.xml.gz" 

#EXTINF:-1  tvg-id=335  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11374-j9jpwgiw-v1/imageContent-11374-j9jpwgiw-m1.png"   group-title=Lifestyle,   DD Punjabi
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000352&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI4MWU5ODgzYS0yNmRjLTQ3NzUtOGQyNC0wODY0NjcxODNmYjYiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ2LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ2LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTIwOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.M3Lh86xKlh_WyTP4erFHp5aR6ZvWLQRYEllYTjUXR8c
https://delta32tatasky.akamaized.net/out/i/1739529.mpd

#EXTINF:-1  tvg-id=22  tvg-logo=""   group-title=,   
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000023&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI2ZDUyNTYyZi0yMzQwLTQ1ZGEtOThjZi05NjY5YTNhYWMyMTUiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ2LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ2LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDA3NywiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.fzL0nRfEpgU51AMZRD6X1z4y57adG1TalMIVHAIOfKM
https://delta31tatasky.akamaized.net/out/i/57073.mpd

#EXTINF:-1  tvg-id=840  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-56386-kfc14w60-v4/imageContent-56386-kfc14w60-m4.png"   group-title=Spiritual,   Shirdi Sai Baba
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000975&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI5ZTRiNWNmNy1kNDk2LTRhNmMtYmVhMC0yOGY4OGJmZjVhYzYiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ2LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ2LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.vtE6zW2XxWwMGM4rSOeVUV6XxZmJvXP5UyVyTKTuiqM
https://delta45tatasky.akamaized.net/out/i/554.mpd

#EXTINF:-1  tvg-id=842  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-56389-kfdgngts-v3/imageContent-56389-kfdgngts-m3.png"   group-title=Spiritual,   Somnath Temple
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000976&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIzZWU3YWVkZC02MGNlLTQzZTAtOTE5ZS0wNmE5OTQ4ZmU0M2MiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ2LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ2LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTI3NCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.HV4gumUr1FzfhaGE3NecJP4PnBBC-sMTJCzTpCZ8IGk
https://delta45tatasky.akamaized.net/out/i/722.mpd

#EXTINF:-1  tvg-id=843  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-56392-kfdh2tao-v3/imageContent-56392-kfdh2tao-m4.png"   group-title=Spiritual,   ISKCON Mumbai
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000977&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIzOGZlNjA0OC02N2MzLTQyNWYtOTgxMC1jODUwNTNhMTcyOTgiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ2LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ2LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAwMSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.nHosvWlkTvz26LuAfFJtElj_Ls5WAip4InEYeU1oQIg
https://delta37tatasky.akamaized.net/out/i/3443253.mpd

#EXTINF:-1  tvg-id=849  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-56496-kfgytl14-v3/imageContent-56496-kfgytl14-m3.png"   group-title=Spiritual,   Kashi Vishwanath Temple, Varanasi
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000985&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI3ZjdlZjQwNi0wMmE3LTRlYzgtYTBmOS00MGJjYzFjNzdmYmUiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ2LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ2LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.CcQCLu3_p5tZ0JfiPlwnihxcEBMqlW9HJ11_kxPaIUQ
https://delta1tatasky.akamaized.net/out/i/5532394.mpd

#EXTINF:-1  tvg-id=191  tvg-logo="http://118.185.56.39/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-795-j5m7axrc-v1/imageContent-795-j5m7axrc-m1.png"   group-title=Entertainment,   DD National
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000206&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIzYmE2NThhMi1jNjEwLTQwODYtYTlmMS1mNzI3MjA2NTNiN2EiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ2LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ2LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTIwOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.RIy-7tVre0ZEDFNhJ_SN-RUPf_D4xOoQW09R8nFzJn0
https://delta12tatasky.akamaized.net/out/i/3569776.mpd

#EXTINF:-1  tvg-id=817  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-52874-k9afcvs0-v2/imageContent-52874-k9afcvs0-m6.png"   group-title=Entertainment,   DD Retro
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000917&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJkYzg5NDQ5YS00MDFhLTQzYjktOTliZi1mOThkZjFiOTFmNTMiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ2LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ2LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzNSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.X4R-y_vsNSYL9eb_O2HL5euV1o13MDRW9RO5w_Lf-n4
https://delta11tatasky.akamaized.net/out/i/2960270.mpd

#EXTINF:-1  tvg-id=818  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-52945-ka1wdss8-v2/imageContent-52945-ka1wdss8-m2.png"   group-title=Entertainment,   Shemaroo TV
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000918&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJiNDc3ZDBjMS1hMjliLTQyMWItYjE3Zi1hNDc1ZWJmY2NmNTIiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ2LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ2LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAwMSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.wthslTT4e3V__ehqlOzOqxS6rH-OVrSLJr_6FKouRq8
https://delta37tatasky.akamaized.net/out/i/2894730.mpd

#EXTINF:-1  tvg-id=326  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11350-j9jpk8pk-v1/imageContent-11350-j9jpk8pk-m1.png"   group-title=Knowledge,   DD Kisan
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000344&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJjM2ExZmFlYS1jNDdiLTQ0YTMtOWU5MS00YjE2OGU0NTBkZDciLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzNSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.gU9Y9oX-G83h2fjoDRjufFjDQGpwIuhjNXFr_uWbuLc
https://delta15tatasky.akamaized.net/out/i/1454898.mpd

#EXTINF:-1  tvg-id=223  tvg-logo="http://118.185.56.39/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-941-j5mhk5fc-v1/imageContent-941-j5mhk5fc-m1.png"   group-title=Sports,   DD Sports
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000236&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIyNTY3NmQwYS1jZTU0LTQ0ZjYtYjI3ZC1lNDk1ZmZkN2MwMTEiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDQ2NCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.Wfg3tgWa5qqmtpPAdkcwRpY3--FsAVOSwagB_GmKbqo
https://delta9tatasky.akamaized.net/out/i/2112645.mpd

#EXTINF:-1  tvg-id=322  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11333-j9joxlw8-v2/imageContent-11333-j9joxlw8-m2.png"   group-title=News,   DD News
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000337&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI0ZTM0ODVlNy0zMTJiLTQ3N2MtYTYxMi03OTAyMzNmN2U0YTEiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTIwOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.MPCcRQ_VrQSa5_3HVkrXQGqMMLEuTkS_y_dOCxvrq-c
https://delta32tatasky.akamaized.net/out/i/1691524.mpd

#EXTINF:-1  tvg-id=662  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-31373-jlx4j6gw-v2/imageContent-31373-jlx4j6gw-m2.png"   group-title=Lifestyle,   Tata Play Family Health
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000701&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI0YTM3NjkxNS1lNjRiLTRmYTgtODkzMC0zOTA2NzE0MTk1MGIiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAwMSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.qhfo_AJljjkvnJ7QnsxYWxQJihE0KBcqUs9w63dz2rI
https://delta12tatasky.akamaized.net/out/i/3569764.mpd

#EXTINF:-1  tvg-id=932  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-64606-krslbshs-v1/imageContent-64606-krslbshs-m2.png"   group-title=News,   Times Now Navbharat HD
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400001083&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI0MzVlMDlkNy1hMzUwLTQyYWQtYjJkYS02NGY3NTNlNDYxZjEiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTc3NSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.HqtP6i6BguupV_PnCQ4lb4wT3WtIw8KhgfxoqtRy_5A
https://delta43tatasky.akamaized.net/out/i/793883.mpd

#EXTINF:-1  tvg-id=950  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-66223-ku9gfjug-v1/imageContent-66223-ku9gfjug-m1.png"   group-title=News,   ET Now Swadesh
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400001101&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJkY2E1ZDE5Yy03OGZhLTQ1YjMtYjA2MS00OTkxYTUwYjkxZDkiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.MgCfKVqToEc93nkKm8StsUg_qp3aTOccaWlESMewnwQ
https://bpprod2linear.akamaized.net/bpk-tv/irdeto_com_Channel_1781/output/manifest.mpd

#EXTINF:-1  tvg-id=213  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-825-j5m9c6c0-v2/imageContent-825-j5m9c6c0-m2.png"   group-title=News,   Sansad TV
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000216&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIyMTlhNDcxNy04MWI0LTRhM2ItYTQ5YS1kNTQzMDg5MTFiZWIiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAwMSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.BMUPeZUaa7odf0EFsScZ7cbL7Urp54RiPFnyQFmnPio
https://delta3tatasky.akamaized.net/out/i/2231635.mpd

#EXTINF:-1  tvg-id=212  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-858-j5ma94ag-v2/imageContent-858-j5ma94ag-m2.png"   group-title=News,   Sansad TV - Rajya Sabha
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000227&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJkYjllYjY3YS1mMjM3LTQyYWEtYTIxMS1jZTkxYTdlOGY0YTkiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzNSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.FPFKMq0HBd1ccA2YX8E63pKvHSdvOayrkqw3JGRoxHw
https://delta7tatasky.akamaized.net/out/i/5708978.mpd

#EXTINF:-1  tvg-id=324  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11344-j9jpg7nc-v1/imageContent-11344-j9jpg7nc-m1.png"   group-title=News,   DD India
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000342&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI0OWIwNTliNC0yZjkyLTQzNzMtYjhkOS0xMGYzNDE5OGQwZWEiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzNSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.LOH_GCRcaYBQA8A8DhnUmDVv-EpVsG7pyB2EC7vTPQY
https://delta32tatasky.akamaized.net/out/i/1739512.mpd

#EXTINF:-1  tvg-id=2  tvg-logo=""   group-title=,   
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000002&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJkMzlkNGU0ZS01M2ExLTQ0MjctOTU4Zi0zMzAxYmExZDRhZGYiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTI3NCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.0LPuP_7ph8PD2ewBOxIwk9IGf5A034jNr54qntqS5Ow
https://bpprod1linear.akamaized.net/bpk-tv/irdeto_com_Channel_275/output/manifest.mpd

#EXTINF:-1  tvg-id=923  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-63764-kr1kzw28-v2/imageContent-63764-kr1kzw28-m2.png"   group-title=Lifestyle,   TravelXP 4K HDR
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400001074&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIyODI1NDdlYi01NDRkLTQ3ZmUtOWU0NS0zMzVkZjc0YzA3ODciLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTI3NCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.wpQ2foMqPbtwB_N2ypGt0Jsm5504zkZJ0hGIeT7To5Y
https://deltatesttatasky.akamaized.net/out/i/308733.m3u8

#EXTINF:-1  tvg-id=316  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11320-j9jlusp4-v1/imageContent-11320-j9jlusp4-m1.png"   group-title=Spiritual,   DD Bharati
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000330&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI4ZmYyYjA5NC0xNjBkLTRkOTItYjY0ZS1lY2Q2ODQ1NTYzZTYiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAwMSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.AaAZEavOfTfdLq_EerEm0uEBdbItu-Awzk3cyNEW1g8
https://delta15tatasky.akamaized.net/out/i/1454813.mpd

#EXTINF:-1  tvg-id=339  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11389-j9jq2ybk-v1/imageContent-11389-j9jq2ybk-m1.png"   group-title=Lifestyle,   DD Uttar Pradesh
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000357&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIyNzNjNTFkNS1kNWIyLTQ5NjUtOTIwMy1iNThhOWM5YmM4YTAiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ3LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ3LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTIwOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.vp-u451tVp34jp4OJuuszbwKbZa6s30wcUfp93dLKvY
https://delta33tatasky.akamaized.net/out/i/2506888.mpd

#EXTINF:-1  tvg-id=317  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11321-j9jlxaz4-v1/imageContent-11321-j9jlxaz4-m1.png"   group-title=News,   DD Bihar
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000331&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIyZjZhOGZlMC1mZmIyLTQyOTMtODQxNy1kNGU5NDk5NTkyMjUiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDQ1NiwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.AOVXJiRvouEnZxy3nUZusdodm6pd3OdlZpdiZvPzNPI
https://delta32tatasky.akamaized.net/out/i/1739499.mpd

#EXTINF:-1  tvg-id=330  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11351-j9jpmdvc-v1/imageContent-11351-j9jpmdvc-m1.png"   group-title=News,   DD Madhya Pradesh
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000347&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI2OGRmM2IzMy00ZDE5LTRhYzItOWE0ZS00MmQxYzU1MDg0YjYiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAwMSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.ifYgJDJLH_yiqYiMnY0pRiUbCIHGbu1bSmp3C2Jtm1w
https://delta40tatasky.akamaized.net/out/i/2274124.mpd

#EXTINF:-1  tvg-id=912  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-62613-koxw351c-v1/imageContent-62613-koxw351c-m1.png"   group-title=Entertainment,   Haryana Beats
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400001063&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJlODQ4ZDJlYS04NDM3LTRlNDAtOWQyNC02YmJiMjQzOGFmYjUiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.BOdMZG8MFhNDgiD3nyEIzQu45xul4OfJTY9DECo9Jy0
https://delta45tatasky.akamaized.net/out/i/139.mpd

#EXTINF:-1  tvg-id=332  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11375-j9jpws3k-v1/imageContent-11375-j9jpws3k-m1.png"   group-title=Knowledge,   DD Rajasthan
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000353&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJlMTQ0OWE1Mi1iMzgyLTRmNDQtYmZjOC1iYTEzMjU0ODg3NDciLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDQ2MiwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.auDwiohyjHM9V4epE4w-IJ-xkK3E396ou1q1FwwQhP0
https://delta15tatasky.akamaized.net/out/i/2627381.mpd

#EXTINF:-1  tvg-id=336  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11378-j9jq0f9s-v1/imageContent-11378-j9jq0f9s-m1.png"   group-title=Knowledge,   DD Sahyadri
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000354&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJlMzVkZTY4MS1iZWFjLTRmZTYtOTM0Mi1mMGJlYTA5MzIwNTMiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.B-eV0WLItlUg1IxFLoLHxAS3A_DA9nL_l6OqxR0QJfw
https://delta38tatasky.akamaized.net/out/i/2051474.mpd

#EXTINF:-1  tvg-id=305  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11287-j9j4tl2w-v2/imageContent-11287-j9j4tl2w-m3.png"   group-title=Spiritual,   Colors Bangla HD
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000319&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIwYzhhNTk3My1kYWVjLTRhMmEtYTQ0Yi1hMzdkZDM1N2JlNmUiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTUyNCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.jgS9VvAY4LOHdyXS5PUdQktxTiRZFr-4TElRrOCyLgc
https://delta32tatasky.akamaized.net/out/i/1727663.mpd

#EXTINF:-1  tvg-id=26  tvg-logo="http://118.185.56.39/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-75-j5fikj0o-v1/imageContent-75-j5fikj0o-m1.png"   group-title=Spiritual,   Colors Bangla
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000025&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJhNGYxZTFlNS0wM2FiLTQ2YjctYjZmYy0wOWVhOGI1NzdiNjIiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTEwNCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.SvDbXghePiEX_IyJct1pNkq55wjZP41qj5wXNUDohG8
https://bpprod1linear.akamaized.net/bpk-tv/irdeto_com_Channel_283/output/manifest.mpd

#EXTINF:-1  tvg-id=522  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11970-j9luk5ag-v1/imageContent-11970-j9luk5ag-m1.png"   group-title=Entertainment,   Zee Bangla HD
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000546&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI3NmNhNTNhOS04ODkwLTRlMGItYWNlNi0zNGFmMzczZWVjMGQiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTUyNCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.9bY6zP7vRSJTVZ-N-Zdoz-rtsojlYkk94K6Dk6R7Ak8
https://delta33tatasky.akamaized.net/out/i/2496587.mpd

#EXTINF:-1  tvg-id=468  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11813-j9kz0vow-v1/imageContent-11813-j9kz0vow-m1.png"   group-title=Entertainment,   Star Jalsha HD
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000492&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI3ZjRjNjg5NC1iNGY4LTRmYjktODFkOS01N2I5MWFjOGU2OTEiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAzMywiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.6h2-PtsldVfe-Omi7SGWRCDSQ0YpOaA_r0CERoyXYa8
https://delta42tatasky.akamaized.net/out/i/1313336.mpd

#EXTINF:-1  tvg-id=34  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-94-j5fjveio-v2/imageContent-94-j5fjveio-m1.png"   group-title=Kids,   SONY AATH
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000033&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJmYjkyYWZmNi02ZWE4LTQ2NzYtYWZmZi1lYTQ3NDYxYTc2MGYiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTExNCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.grMVcgI9cpHv_g_F7xFvJSkcrb3x1_S4szzNQCzzb0A
https://delta7tatasky.akamaized.net/out/i/4326683.mpd

#EXTINF:-1  tvg-id=537  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11514-j9jtp5tk-v1/imageContent-11514-j9jtp5tk-m2.png"   group-title=Thriller,   Jalsha Movies HD
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000565&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIxOGM0M2IyMi1hMDk4LTRkZGEtYmU0OC0yYzhhZjQ4NjcyZTkiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAzMywiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.dsfdYsfuQwcvjLOOWb71q-aNOVT-iM1n5fipxjS5ob0
https://delta40tatasky.akamaized.net/out/i/2326416.mpd

#EXTINF:-1  tvg-id=254  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11009-j8xbk7js-v1/imageContent-11009-j8xbk7js-m1.png"   group-title=Drama,   Zee Bangla Cinema
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000268&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI2ZjMzMWYxYy04ZDk5LTQzMDAtODc3Yy01NzY1MWE5Y2Y3NWEiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTkwMywiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.B8Sl49cS1fse11eFsQd3Yzs4MxH2h_tos5BXCXv7tzg
https://delta16tatasky.akamaized.net/out/i/2834224.mpd

#EXTINF:-1  tvg-id=896  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-62141-knicrr2g-v1/imageContent-62141-knicrr2g-m1.png"   group-title=Drama,   Colors Bangla Cinema
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400001045&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI0ZmYxYjM3ZC0zMDhhLTRlZDMtOGMzYS1kYmZlNTM5YmVkY2YiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ4LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ4LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAwMSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.gjt2VNq5PZMVR5pW06YUZpYz6E64KU_tMPrQ0mtYlts
https://bpprod1linear.akamaized.net/bpk-tv/irdeto_com_Channel_1305/output/manifest.mpd

#EXTINF:-1  tvg-id=102  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-321-j5jl5g5k-v2/imageContent-321-j5jl5g5k-m2.png"   group-title=News,   ABP Ananda
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000101&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJiMTMzYmIzZi04YWY0LTQ3NTUtOTczZS0xYWI1YWVlMGYwY2EiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTM2OCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.-rGfdvEX6O5TVtTI1_U1VWGcBG_Ws7JkNHsnVfOxXTM
https://delta6tatasky.akamaized.net/out/i/2108737.mpd

#EXTINF:-1  tvg-id=258  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-9031-j7u3nz6w-v1/imageContent-9031-j7u3nz6w-m1.png"   group-title=News,   Zee 24 Ghanta
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000272&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJkODZkNzNjMC04MzY3LTRlNWItYWJiNC1hMjkxMzExODYxZmQiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTEyOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.ObbjlKAzOdJC-R9z2FDQAdcN-DRF4MZZzQSj4vOI858
https://delta16tatasky.akamaized.net/out/i/2903691.mpd

#EXTINF:-1  tvg-id=23  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-22186-jenuxy6g-v2/imageContent-22186-jenuxy6g-m5.png"   group-title=News,   News18 Bangla
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000018&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIzZWMzY2RkZS02YmQ2LTQ4N2ItODQ5ZS0yMTQ4ZjY1NWY3ODMiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTMxNCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.J3pZVopnAJkSrjQpqZnCLvYs-FuIXusYD8zfcmULtWE
https://delta4tatasky.akamaized.net/out/i/3141844.mpd

#EXTINF:-1  tvg-id=873  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-59401-kjudpa1c-v2/imageContent-59401-kjudpa1c-m3.png"   group-title=Entertainment,   TV9 Bangla
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400001018&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI0MGZlMTYyZS1kNmE3LTQxMzEtOGQ3ZC02NzBlMzU3NDdiNjciLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAwMSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ._2V8y6ooV1WUT69TUKDf09o4aNNqvCSLi1qPENbZDWI
https://bpprod1linear.akamaized.net/bpk-tv/irdeto_com_Channel_1149/output/manifest.mpd

#EXTINF:-1  tvg-id=314  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11314-j9j8kcxk-v1/imageContent-11314-j9j8kcxk-m1.png"   group-title=Lifestyle,   DD Bangla
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000328&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJiZWNhNmVmMi0xZTliLTRlNmItYjY0Mi0xMTc3YjE5Zjg0YTQiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAwMSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.7T3N43kVAMyvHEbgpiSYxEQwS6LomZWtTHNf1eRCq1o
https://delta2tatasky.akamaized.net/out/i/4450742.mpd

#EXTINF:-1  tvg-id=337  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11381-j9jq1pkg-v1/imageContent-11381-j9jq1pkg-m1.png"   group-title=Knowledge,   DD Saptagiri
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000355&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJjYmRjZmNkMi02YjRiLTRlMmItODM2OC0yODdkNGYyZTBjYzAiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTIwOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.0lcx9SJPHIh188yLUW3APDOwfMzsyUBfIu4TzVpkP8Q
https://delta32tatasky.akamaized.net/out/i/1739517.mpd

#EXTINF:-1  tvg-id=548  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11392-j9jq3lgw-v3/imageContent-11392-j9jq3lgw-m2.png"   group-title=Knowledge,   DD Yadagiri
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000358&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIxMzMzMmNmNy1lNzk3LTRkNTAtOGU4ZC1jNzgzYjIwYWM5NzAiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.QqJDaSY3IJRvQzeIIUSpRr7D7cQCceaG8egGjjGimbU
https://delta33tatasky.akamaized.net/out/i/4144008.mpd

#EXTINF:-1  tvg-id=914  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-62861-kpdll0iw-v1/imageContent-62861-kpdll0iw-m1.png"   group-title=Sports,   Sony Ten 4
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400001065&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI5NmQ2MWRjZC04NDQyLTQyYmUtYjRlMC0yYTZmY2NmMDYzNTkiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.N6t7kFB-czL_DZ0NQKbJ63jmvOQThUlJNjZv_sc-VT8
https://delta31tatasky.akamaized.net/out/i/41.mpd

#EXTINF:-1  tvg-id=334  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11369-j9jpvzjs-v1/imageContent-11369-j9jpvzjs-m1.png"   group-title=Spiritual,   DD Podhigai
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000351&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJjODNlOWYxYy1iZmExLTQ4OTQtYmY2My0xODI5MjNhNmMyM2IiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzNSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.Wus5DLpnojo1DRvaV-4OI6WHQZbHSGlASwEh2z6Ylyg
https://delta15tatasky.akamaized.net/out/i/1454859.mpd

#EXTINF:-1  tvg-id=810  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-52310-k7bd8ixk-v2/imageContent-52310-k7bd8ixk-m4.png"   group-title=Drama,   Zee Picchar
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000901&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJiZjBhNzlmYy01YjU2LTRjMTItODU4Ny04YjRkZjZkNjk0MGMiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTA4MywiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.uqsnYyhGhSb9z16G23NPQ7RQkcNTMVmzst7mNylMIkM
https://delta14tatasky.akamaized.net/out/i/2721311.mpd

#EXTINF:-1  tvg-id=913  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-62858-kpdlcyeg-v2/imageContent-62858-kpdlcyeg-m2.png"   group-title=News,   News 1st
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400001064&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIyNjU4MDM2Zi04MDczLTRiZTAtOTIzMC0yODczOTgwNDg0NGIiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzNSwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.9g1pZ5v4dbbPezZxZJKn7CIyAVEpHZQFnr1jcbIwdIQ
https://bpprod2linear.akamaized.net/bpk-tv/irdeto_com_Channel_1320/output/manifest.mpd

#EXTINF:-1  tvg-id=321  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11338-j9jozdxs-v1/imageContent-11338-j9jozdxs-m1.png"   group-title=Knowledge,   DD Chandana
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000338&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIwMjc3OGM4My0yNDIwLTQ4ODktYmQ4Yi03Nzc3YjhjYjczNDUiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMDIwOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.KDV9t9bihJ5MOfV1UVFolV75dXmlruWOFltoGo5klfM
https://delta38tatasky.akamaized.net/out/i/2051449.mpd

#EXTINF:-1  tvg-id=323  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11341-j9jpdu00-v1/imageContent-11341-j9jpdu00-m1.png"   group-title=News,   DD Girnar
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000341&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJlNmMxOTY4Mi1jZTQwLTQ3YjktOWVlNS1lMTJmMTE5ZWI1M2YiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTUyMywiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.PHKJWAGwetQ1cJ5aOZMvOuK3UHUFRPCi-qV1mymcZEA
https://delta42tatasky.akamaized.net/out/i/110.mpd

#EXTINF:-1  tvg-id=333  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-11366-j9jpvkw0-v1/imageContent-11366-j9jpvkw0-m1.png"   group-title=Knowledge,   DD Odia
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000350&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJkNGJiNWYxYy0xMzQwLTRlZjQtYmM1OC00ZmU5ZGI5MDY3YTQiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTIwOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.I3qqMqnYePznPTppRa27h4sgmLmjVzItcpHbRpq4M08
https://delta15tatasky.akamaized.net/out/i/1454829.mpd

#EXTINF:-1  tvg-id=820  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-53493-kaz5h2kg-v2/imageContent-53493-kaz5h2kg-m4.png"   group-title=Knowledge,   KITE Victers
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000922&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiJiOTFjOGRjOS0yNDMwLTQ1NDQtODM3YS1kNGI2MDcwMDA0MzUiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjQ5LCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODQ5LCJlbnQiOlt7ImJpZCI6MTAwMDAwMTAzOCwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.YaNcn35kfNsgkuGlEc9mSGvG_EXgoQzaYFBuY-JkXSE
https://delta34tatasky.akamaized.net/out/i/4121224.mpd

#EXTINF:-1  tvg-id=571  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-12125-j9oq3d2o-v5/imageContent-12125-j9oq3d2o-m6.png"   group-title=Spiritual,   Tata Play Punjab De Rang
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000602&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiIyMjFkNmM5OC00YzdhLTQwOTctOTUzYi00MDhlYjVhNWQ2YzIiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjUwLCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODUwLCJlbnQiOlt7ImJpZCI6MTAwMDAwMDYyNiwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.06iv64W0rvh2YKa-cHCwMwkvJ2ifKqlKi21_iXBWgmA
https://delta31tatasky.akamaized.net/out/i/194.mpd

#EXTINF:-1  tvg-id=787  tvg-logo="http://tank.tskytech.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-48498-k3zd4bsg-v1/imageContent-48498-k3zd4bsg-m3.png"   group-title=News,   ANB NEWS
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://tatasky.live.ott.irdeto.com/Widevine/getlicense?CrmId=tatasky&AccountId=tatasky&ContentId=400000871&ls_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNvbnRyb2xfc2lnbmluZ19rZXlfcHJvZHVjdGlvbl8xNjMwMDA1NDQ4NDE5In0.eyJzdWIiOiIxMTA3NjA4OTE5IiwiaXNlIjp0cnVlLCJqdGkiOiI4NmM4M2VhOC02YzI4LTQwNGUtOGNlNy00ODMyYTkwNTM3ZDEiLCJhaWQiOiJ0YXRhc2t5IiwiZXhwIjoxNjQ2MTM5MjUwLCJuYW1lIjoiU1VKSVAgSEFMREVSIiwiaWF0IjoxNjQ2MDUyODUwLCJlbnQiOlt7ImJpZCI6MTAwMDAwMDAwMiwiZXBpZCI6IlN1YnNjcmlwdGlvbl9Nb2JpbGVfU3RyZWFtaW5nIn1dLCJpc3MiOiJUVE4ifQ.BrgObhpFSiRBQxQ7RdHhfDC1ckSCWDwH1P9zSGzxMz4
https://delta35tatasky.akamaized.net/out/i/4452806.mpd

